### ISSUE TITLE
TF2 crash after injecting

### ISSUE THREAD

**Issue by PSSGAMER** [nullworks/cathook#1560]
Cathook instantly crashes tf2 as soon as I inject it. My is zorin lite.

also the gui is different. I downloaded it from the guide and it has a broad layout with the only option being attach. It might be that the link is not up to date is is it something else causing the instant crash?

**Comment by BenCat07** [comment]
Zorin lite is unsupported, which is why it uses binary mode, a precompiled binary gets injected. The problem here is that that binary is compiled on Ubuntu, and it seems your OS has outdated core libraries, causing it to crash upon attach. Either you manually install all the packages needed to compile it manually and switch to source mode in the GUI's menu tab, or you do not use zorin lite.

**Comment by PSSGAMER** [comment]
I’ll go with option 1. Can you please teach me how to do it?

**Comment by BenCat07** [comment]
i have no idea how your distro works. Look at the install dependencies file in the scripts folder and find equivalent packages for your OS

**Comment by iraizo** [comment]
Closed due to inactivity/unsupported distro
