### ISSUE TITLE
Cathook won't compile

### ISSUE THREAD

**Issue by fartzgaming** [nullworks/cathook#1584]
## System Information
**OS: Pop OS**  
**DE: Gnome**  
**Cathook Version: Cathook-GUI**  

## Logs / Crash Report  
[CMakeError.log](https://github.com/nullworks/cathook/files/7563460/CMakeError.log)
[CMakeOutput.log](https://github.com/nullworks/cathook/files/7563461/CMakeOutput.log)

## Description  
I can't compile Cathook and the same errors keep showing. How do I fix this?

## Steps to reproduce  
- [x] I am able to consistently reproduce this error

It happens every time I click install or update.

**Comment by Zanthed** [comment]
You're missing dependencies that Pop_OS doesn't provide in their main repositories.

Add the Ubuntu repos listed at the bottom: https://apt.pop-os.org/

Try re-running ./install-all

**Comment by fartzgaming** [comment]
> You're missing dependencies that Pop_OS doesn't provide in their main repositories.
> 
> Add the Ubuntu repos listed at the bottom: https://apt.pop-os.org/
> 
> And retry.

Now I'm getting a new error. Is it progress? I don't know.
[CMakeError.log](https://github.com/nullworks/cathook/files/7563672/CMakeError.log)
[CMakeOutput.log](https://github.com/nullworks/cathook/files/7563673/CMakeOutput.log)

**Comment by Zanthed** [comment]
Try manually installing the dependencies:

`sudo apt install build-essential git g++ g++-multilib libboost-dev gdb libsdl2-dev:i386 libfreetype6-dev:i386 cmake dialog rsync curl`

**Comment by fartzgaming** [comment]
libc6-dev:i386 : Depends: linux-libc-dev:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Zanthed** [comment]
Typical of Ubuntu-derivatives. Problems like these are awful because the error message is completely ambiguous and unhelpful.

It honestly would be easier to switch to a different distro that's more competent like actual Ubuntu or Arch Linux. Or you can do some Googling and try solving that error yourself.

**Comment by fartzgaming** [comment]
I'll just use an Ubuntu VM to compile cathook than transfer everything to my actual PC. I like Pop OS.

**Comment by BenCat07** [comment]
unlikely to work due to you being required to actually have the libs installed.

**Comment by Zanthed** [comment]
I don't think that would work. Not everything is compiled statically which is why a universal Cathook binary doesn't exist. Some libraries are also necessary to inject.

The compiler also uses `-march=native` so unless you set your processor to the host's, you might experience slower performance, if it does even inject, due to the compiler using virtual machine processor-specific code.

**Comment by fartzgaming** [comment]
Ubuntu VM?

**Comment by Zanthed** [comment]
No. As I said, not everything is compiled statically into the binary. Some libs are also required to inject itself.

**Comment by Zanthed** [comment]
Solving this distro issue is out of scope in here. You need to solve it yourself, switch to a more competent distro that doesn't frankenUbuntu and cause packages to break, or ask someone for distro support in the Telegram.

These absurd apt issues are common in Pop_OS.

**Comment by fartzgaming** [comment]
Maybe I will switch. Is Manjaro a good distro? I just want something that is fast, stable, works out-of-the-box, and relatively easy to use. CathookOS seems kinda sketchy.

**Comment by helm7x7** [comment]
i got the same error yesterday, i found it was cmake, and had to build and compile it from source " wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz " i followed this guide "https://linuxhint.com/install-cmake-on-debian-10/"  ( because on debain ) and it worked for me, any other errors, i removed cathook then re-pulled from github and verified my tf2 files - i hope this helps! :D

**Comment by BenCat07** [comment]
> i got the same error yesterday, i found it was cmake, and had to build and compile it from source " wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz " i followed this guide "https://linuxhint.com/install-cmake-on-debian-10/" ( because on debain ) and it worked for me, any other errors, i removed cathook then re-pulled from github and verified my tf2 files - i hope this helps! :D

Debian has the required dependencies, so it has to be a different error

**Comment by Zanthed** [comment]
> i got the same error yesterday, i found it was cmake, and had to build and compile it from source " wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz " i followed this guide "https://linuxhint.com/install-cmake-on-debian-10/" ( because on debain ) and it worked for me, any other errors, i removed cathook then re-pulled from github and verified my tf2 files - i hope this helps! :D

Unrelated to the main issue. OP has Pop OS and I already included CMake in the Debian dependencycheck script.

**Comment by iraizo** [comment]
Closed due to inactivity
