### ISSUE TITLE
Good job faggot... read more

### ISSUE THREAD

**Issue by GravelPootis1** [nullworks/cathook#407]
"*DEAD* lagger bot 4 :  Lagbots - Rage? t.me/nullifiedcat
MatesV4 was automatically assigned to team BLU
(Voice) LarguZzZ***: MEDIC!
*DEAD* lagger bot 4 :  Lagbots - A living proof that Source Engine is shit!
Nainfrex has joined the game
C1 Ska1zz has joined the game
*DEAD* lagger bot 4 :  Lagbots - Running on CatHook, made by Nullifiedcat!"

Now send me anti-lag code or i report it to game dev and he will patch it quickly.
You can lag faggots but not me.

**Comment by GravelPootis1** [comment]
Ok faggot. It actually gets patched in hours lol. why the fuck you spam that shit messages than laging server silently, if game dev watch src, jesus with you

**Comment by cheddar-cheeze** [comment]
LOL triggered gamer

**Comment by Marc3842h** [comment]
Hi,

This issue seems more like a issue between you and people that use this software. Please get in touch with them as this issue section here on GitHub is for issues and requests with the codebase, not for your lagging problems.

Please note that your issue may be considered spam and offensive to fellow visitors of this repository. Posting spam and offensive content on public repositories is against GitHubs terms and policies and may result in your account getting flagged by GitHub's anti-spam. 

Additionally, your issue and comments here are breaking our [Code of Conduct](https://github.com/nullworks/cathook/blob/master/CODE_OF_CONDUCT.md). Every contributor to this repository is required to follow this Code of Conduct before participating in this discussions on this repository. Please read them before participating in further discussions on this repository.

**Comment by mrsteyk** [comment]
You are not the smartest person here, lol. Valve wont patch this only because of you, since tf2 dev team is fucking lazy. It took them like 2 years to fix simple time shifting exploits. And most of them still work ecks dee. And theres no anti-lag code other than sm plugin, which valve ofc wont use.
