### ISSUE TITLE
(Question) What happened to the all-in-one install command?

### ISSUE THREAD

**Issue by duckymomo360** [nullworks/cathook#439]
If it still exists, can I have it? Because I'm not too smart when it comes to Linux.
Also, What type of Linux should I use? I'm currently using Ubuntu.

**Comment by TotallyNotElite** [comment]
Ubuntu is fine (and recommended). I'm currently installing cathook on a friends PC and making a list of dependencies for you to install. Hang tight :) The rest of the process should be pretty straight forward. If you need help just @Elite me in https://t.me/nullifiedcat

**Comment by BenCat07** [comment]
I will readd one today

>

**Comment by BenCat07** [comment]
ye it will also auto install deps too

Am 16.05.2018 08:19 schrieb ".bread" <notifications@github.com>:

make a bash script that just executes the commands to compile cathook?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nullworks/cathook/issues/439#issuecomment-389407631>,
or mute the thread

**Comment by BenCat07** [comment]
Depends, our discord got felrted again just today

duckymomo360 <notifications@github.com> schrieb am Mi., 16. Mai 2018, 20:48:

**Comment by BenCat07** [comment]
readded
