### ISSUE TITLE
Medic Followbot & Auto Heal Improvements

### ISSUE THREAD

**Issue by khubik** [nullworks/cathook#789]
These features may enchance autohealing Medic followbots:
• Auto Heal Friends-Only mode
• Auto Heal priority (health percent, health value)
• Followbot Follow Friends option
• Auto Heal Pop Übercharge on "Activate Über" voice command from heal target

**Comment by EricSmith17** [comment]
You gay

**Comment by BenCat07** [comment]
last point is mentioned in #761

**Comment by BenCat07** [comment]
> • Auto Heal priority (health percent, health value)

What does this mean?

**Comment by SylveonBottle** [comment]
> > • Auto Heal priority (health percent, health value)
> 
> What does this mean?

I believe you can currently set autoheal to target users with lower HP. But this isn't enabled by default.

OP could either be talking about making it so that this thing will heal based on the health number (or percentage, which doesn't make sense - you should heal a soldier at 80% health rather than a heavy at 50% health because the soldier still has less health or something like that), or he could be suggesting to make it heal by least health by default.

**Comment by BenCat07** [comment]
> > > • Auto Heal priority (health percent, health value)
> > 
> > 
> > What does this mean?
> 
> I believe you can currently set autoheal to target users with lower HP. But this isn't enabled by default.
> 
> OP could either be talking about making it so that this thing will heal based on the health number (or percentage, which doesn't make sense - you should heal a soldier at 80% health rather than a heavy at 50% health because the soldier still has less health or something like that), or he could be suggesting to make it heal by least health by default.

Currently we autoheal people based on percent of HP left... i should just add a weight system per class with menu entry
