### ISSUE TITLE
[TODO] Add a "Crit Saving" Mode

### ISSUE THREAD

**Issue by BenCat07** [nullworks/cathook#791]
Basically, this feature will do two things:
- On melee weapons, when no enemy/backtrack position is within 400 Hammer Units, prevent crits in order to fill the crit bucket
- On non melee, prevent crits when crit key is not pressed, in order to charge the crit bucket

**Comment by Riflerat** [comment]
I was thinking almost same. Your issue is great, and I have an idea that is close to yours.:
I watched, the crits are more rare when randomly happen than I press the button dedicated for "forced" crit. (On other hands: emptying crit bucket happens more often when forced with a pressed crit button). When bot running, ofc I can't press the crit button, that' why I suggest option for "forced auto crit".
Of course crits are limited in game and your issue I suggested can prevent crits as you wrote in your issue so I issue the following options:
[] Force crits on melee
[] Force auto crits
